# your domain
domain: example.com   # or example.com:9443 for reserve proxy server
port:                 # default 12580
# subscribe pool check
pool-files-check: # v0.7.15 default false
pool-files:  # v0.7.15 When the readiness check is executed, it will output a source.yaml file in the same directory. The script will automatically exclude any duplicate URLs.
#  - type: txt # 1.txt,Each URL should be placed on a separate line
#    url:  https://example.com/config/source.txt # use web file
#  - type: yaml # 2.yaml ,The content of the file should be identical to the source.yaml file.
#    url: https://example.com/config/source.yaml # use web file
#  - type: yaml # use local file
#    url: source.yaml # local file

# source list file
source-files:
  # use local file
  - source.yaml
  # use web file
  # - https://example.com/config/source.yaml

# ======= 可选项，留空使用default值  ======= #

#====Postgresql database info ====#
database_url: ""

#==== Interval between each crawling ====#
crawl-interval:             # v0.5.x default 60 (minutes)
#crontime:                  # v0.4.x default 60 (minutes). Deprecated in the newest version
healthcheck-timeout:        # default 5 (seconds)
healthcheck-connection:     # default 500. The number of health check connections simultaneously

#==== Speed test ====#
speedtest: false            # default false. Warning: this will consume large network resources.
speedtest-interval:         # default 720 (min)
speed-timeout:              # default 10 (seconds).
speed-connection:           # v0.7.2 default 5. The number of speed test connections simultaneously
#connection                 # v0.7.1 and beblow

#==== Active proxy speed test ====#
active-interval:            # default 60 (min)
active-frequency:           # default 100 (requests per interval)
active-max-number:          # default 100. If more than this number of active proxies, the extra will be deprecated by speed

#==== Cloudflare api ====#
cf_email: ""
cf_key: ""

#==== stream test support disney+ and netflix ====
stream-max-connect: 500         # v0.7.14 default 500
netflix-test: true          # v0.7.14 default false
disney-test: true           # v0.7.14 default false