name: docker

on:
  push:
    tags:
      - '**'

#jobs:
#  build:
#    name: Build
#    if: startsWith(github.ref, 'refs/tags/')
#    runs-on: ubuntu-latest
#    steps:
#      - name: Set up QEMU
#        if: startsWith(github.ref, 'refs/tags/')
#        uses: docker/setup-qemu-action@v1
#      - name: Set up Docker Buildx
#        if: startsWith(github.ref, 'refs/tags/')
#        uses: docker/setup-buildx-action@v1
#      - name: Check out code into the Go module directory
#        if: startsWith(github.ref, 'refs/tags/')
#        uses: actions/checkout@v3
#      - name: Docker login
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#      - name: Build and push Docker images
#        if: startsWith(github.ref, 'refs/tags/')
#        uses: docker/build-push-action@v4
#        with:
#          push: true
#          platforms: linux/amd64
#          context: .
#          tags: ${{ secrets.DOCKER_USERNAME }}/proxypool:latest
jobs:
  amd64_build:
    name: Build AMD64 Image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/setup-buildx-action@v1
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Build and push Docker images
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64
          context: .
          tags: ${{ secrets.DOCKER_USERNAME }}/proxypool:latest

      - name: Replace tag without `v`
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/github-script@v6
        id: version
        with:
          script: |
            return context.payload.ref.replace(/\/?refs\/tags\/v/, '')
          result-encoding: string

      - name: Build release and export
        id: build_rel
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          context: .
          tags:  ${{ secrets.DOCKER_USERNAME }}/proxypool:${{steps.version.outputs.result}}
          outputs: type=image,push=true

      - name: Save digest
        if: github.ref == 'refs/heads/master'
        run: echo ${{ steps.build.outputs.digest }} > /tmp/digest.txt

      - name: Save release digest
        if: startsWith(github.ref, 'refs/tags/')
        run: echo ${{ steps.build_rel.outputs.digest }} > /tmp/digest.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: digest_amd64
          path: /tmp/digest.txt
